### ISSUE TITLE
Add redirects to staging site

### ISSUE THREAD

**Issue by chrismclarke** [IDEMSInternational/parenting-app-ui#131] opened 2020-11-24 19:44 UTC
Currently direct navigation breaks because all urls should be served via the main index.html. I'm not sure if the load balancer supports a rewrite to correctly handle a single-page-app, or if we will need to fall back to firebase or netlify for hosting (still building on github actions) as mentioned in #110.

Might be of use: https://cloud.google.com/load-balancing/docs/https/setting-up-url-rewrite

**Comment by michaelclapham** [comment] 2020-11-24 19:49
Duplicate of #130

**Closed by michaelclapham** 2020-11-24 19:49 UTC
