### ISSUE TITLE
[BUG] Disable feedback on feedback pop-up

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#1790] opened 2023-02-13 10:30 UTC
PR https://github.com/IDEMSInternational/parenting-app-ui/pull/1783 re-introduces the issue of being able to give feedback on the feedback pop-up (first observed in https://github.com/IDEMSInternational/parenting-app-ui/pull/1603#pullrequestreview-1193256830).  

[screen-capture (32).webm](https://user-images.githubusercontent.com/74557272/218420285-47d1b997-c79a-46bf-b418-8871f34ce58b.webm)

**Comment by chrismclarke** [comment] 2023-02-13 20:20
This is quite a strange one. There is a weird bug where if we try to disable the feedback mode as the popup opens, the feedback _enabled_ checkbox changes which actually triggers it to enable again.

I know things were working differently before, however I think this is possibly due to a regression issue in the 3rd party ionic components package we use as opposed to specific code changes.

This is actually one of the specific behaviours addressed in the upcoming release for Ionic 7, so I'd say if we can hold off on any fix it might be better to wait until the release is marked as stable and upgrade to fix it properly, instead of hacky workarounds
https://ionic.io/blog/announcing-the-ionic-7-beta

Does that sound reasonable to you @esmeetewinkel or is this definitely a high-priority issue?

**Closed** 2023-03-06 14:40 UTC
Labels: bug, needs discussion
