### ISSUE TITLE
[BUG] iOS button shadow 

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#2287] opened 2024-04-09 08:36 UTC
**Describe the bug**
card style button shadow is inconsistent and/or intersects the button, depending on scrolling behaviour.

**App version**
v0.16.29 iOS 

**To Reproduce**
Access any article template on PLH Facilitator MX

**Screenshots and videos**
![image](https://github.com/IDEMSInternational/parenting-app-ui/assets/74557272/da3a9e9a-e035-43d1-bf63-b2341f5d67bd)

**Comment by esmeetewinkel** [comment] 2024-04-09 08:36
Possibly linked to #2274

**Comment by jfmcquade** [comment] 2024-04-10 11:26
On the [comp_button](https://docs.google.com/spreadsheets/d/1OmgZICjM5EMT1KgLOU_ovDljRF_SPlpQAgkKWPrNX0s/edit#gid=569531329) template, the first two "Button card" examples reliably lose some styling when scrolling them off the page and then back again:

https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/4744f295-9ef0-4051-85ae-df63ee2c967c

**Comment by jfmcquade** [comment] 2024-04-11 16:07
Can be replicated in the Safari browser on macOS:

<img width="400" alt="Screenshot 2024-04-11 at 17 06 36" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/59249262-320a-4f97-a1e4-3de4efef6be8">

**Comment by jfmcquade** [comment] 2024-04-25 14:30
This should be fixed by #2302, but I'll add some extra details here in case they prove useful should similar issues emerge:

Following from the [discussion](https://github.com/IDEMSInternational/parenting-app-ui/pull/2288#issuecomment-2050057412) on #2288, I returned to this issue and found the root cause to be as elusive as ever. Setting various combinations of elements to `position: relative` seemed to have no effect. 

It's notable that the version of the card button with a toggle bar within it does not seem to have this issue. However, I was unable to replicate this by adding child elements to the other buttons (I thought that by adding a nested child with `position: absolute` to the `ion-button` with `position: relative` might resolve the issue, but it persists). 
<img width="240" alt="Screenshot 2024-04-25 at 14 59 34" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/3f1107e2-a470-4b8b-ba87-6cf0b9a0aebb">

When the bug is present, i.e. when the background of the button is not visible, the visual result is the same as if the `--background` variable is passed with any invalid value, e.g. `undefined`. Setting the background explicitly, rather than via the `--background` CSS variable that ionic exposes on the `ion-button`, seems to resolve the issue, suggesting that the variable is not being handled correctly. However, there is more going on: when the bug is present, the shadow around the button is less dark than that around the buttons when the bug is not present. This can be replicated by removing a drop-shadow applied to the element.

**Closed** 2024-05-07 08:57 UTC
Labels: bug
