### ISSUE TITLE
Removing hardcoded assets

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#999] opened 2021-09-03 11:04 UTC
**Details**
All assets in the app should be loaded from the [plh_assets](https://drive.google.com/drive/folders/1dp9QAQ84m8pm0IBQTSPXe1ramyynKPNn) Google Drive folder. Currently there are still some hardcoded assets in the repo. These should be removed (taking some care not to have any knock-on effects).

**Additional comments**
Most assets in the app are already loaded from the plh_assets folder. I can think of two cases in which there may be hard-coded assets still in use:
1. The splash screens 
2. The default timer ping

**Comment by chrismclarke** [comment] 2021-09-03 23:10
Just to add some technical clarification, all assets within the `packages/plh_data/assets` folder are copied to the `src/assets` folder as a precompile stage when preparing to run the app locally or create a build, but they are never physically copied on the local harddrive (and so should only appear in git only in the plh_data folder). 

HOWEVER, we do have a hardcoded `src/assets/plh_assets` which used to be used, and in theory will be getting merged with the files coming from the google drive. If all the files are placed correctly on google drive we should be able to safely to delete the `src/assets/plh_assets` folder, however this should be confirmed either looking at these files manually, or deleting and testing for any changes.

From the src code, it seems the only hardcoded `assets/plh_assets` are in the old chat feature so I think safe to remove
![image](https://user-images.githubusercontent.com/10515065/132072781-d8744b08-b4c5-4beb-b094-5902b2700226.png)

So the only room for error would be from within templates that reference files that were never put on the google drive, but went unnoticed because the hardcoded copy exists.

**Comment by ehmadzubair** [comment] 2021-09-07 11:46
@zulkifelff

**Comment by chrismclarke** [comment] 2021-09-07 21:35
@zulkifelff - I forgot to discuss this one on the call today. I think it is lower priority so we can probably just discuss next week, although if you did have any questions before then feel free to reach out to me on slack.

**Comment by chrismclarke** [comment] 2021-11-12 21:04
Reassigning to myself as I'm working on assets anyway currently

**Closed** 2021-11-17 16:15 UTC
